import React from "react";
import { 
  Shield, 
  Eye, 
  Lock, 
  UserCheck, 
  Database, 
  Globe, 
  FileText, 
  Calendar, 
  Clock, 
  Smile, 
  Mail 
} from "lucide-react";

const Privacy = () => {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  React.useEffect(() => {
    scrollToTop();
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50 pt-8 pb-16">
      {/* Full Width Wrapper */}
      <div className="w-full px-4 sm:px-8 lg:px-16 xl:px-24">
        
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 rounded-2xl mb-6">
            <Shield className="w-8 h-8 text-blue-600" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-4">
            Privacy Policy
          </h1>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 text-gray-600 text-base">
            <p className="flex items-center gap-1.5">
              <strong>Company:</strong> Webix Infotech India Pvt. Ltd.
            </p>
            <span className="hidden sm:inline text-gray-300">|</span>
            <p className="flex items-center gap-1.5">
              <strong>Effective Date:</strong> January 2026
            </p>
          </div>
        </div>

        {/* Content Box - Full Width Design */}
        <div className="w-full bg-white rounded-3xl shadow-xl p-8 sm:p-12 lg:p-16 space-y-10">
          
          {/* Main Top Paragraph */}
          <p className="text-gray-700 leading-relaxed text-lg border-b border-gray-100 pb-6">
            Webix Infotech India Pvt. Ltd. ("Webix Infotech," "we," "us," or "our") values your privacy and is committed to 
            protecting your personal information with the highest standards of transparency and security. This Privacy 
            Policy outlines our compliance frameworks, guidelines, and methodologies regarding how we collect, use, 
            store, process, disclose, and safeguard your details when you interact with our official website 
            (webixinfotech.com), mobile applications, products, and tech-driven corporate services.
          </p>

          {/* 1. Introduction & Scope */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <FileText className="w-6 h-6 text-blue-600" />
              1. Introduction & Scope
            </h2>
            <p className="text-gray-700 leading-relaxed">
              This document governs the collection of data generated by users visiting our digital infrastructure or 
              partnering with us for project development. This policy specifically addresses informational handling for digital 
              visitors, clients, and prospective associates. It does not look to overcomplicate our operational boundaries 
              with unnecessary elements irrelevant to our service ecosystem, but rather focuses heavily on accurate, robust 
              Indian and global digital processing safeguards.
            </p>
          </section>

          {/* 2. Information We Collect */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Database className="w-6 h-6 text-blue-600" />
              2. Information We Collect
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              We collect specific sets of data depending strictly on the nature of your interaction with Webix Infotech. This 
              data falls into two fundamental categories:
            </p>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-4">
              <div className="bg-slate-50 rounded-2xl p-6 border border-gray-100">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <span className="w-2 h-2 bg-blue-600 rounded-full"></span>
                  A. Voluntarily Provided Personal Data
                </h3>
                <ul className="space-y-3 text-gray-700 list-disc list-inside pl-1">
                  <li>
                    <strong className="text-gray-900">Identity & Contact Attributes:</strong> Full legal names, corporate designations, professional email communication streams, contact numbers, and commercial physical addresses provided during contact forms or consultations.
                  </li>
                  <li>
                    <strong className="text-gray-900">Project Scope Metrics:</strong> Technical requirements, system parameters, architectural inputs, and documentation shared by corporate clients for project estimation.
                  </li>
                </ul>
              </div>

              <div className="bg-slate-50 rounded-2xl p-6 border border-gray-100">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <span className="w-2 h-2 bg-blue-600 rounded-full"></span>
                  B. Automatically Aggregated Data
                </h3>
                <ul className="space-y-3 text-gray-700 list-disc list-inside pl-1">
                  <li>
                    <strong className="text-gray-900">Technical Infrastructure Markers:</strong> Server log captures, Internet Protocol (IP) addresses, dynamic geolocation region tracking, browser variants, and system software builds.
                  </li>
                  <li>
                    <strong className="text-gray-900">Behavioral Telemetry & Analytics:</strong> Clickstreams, duration of page visits, exit-path analytics, and internal links accessed during system engagement.
                  </li>
                </ul>
              </div>
            </div>
          </section>

          {/* 3. How We Use Information */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <UserCheck className="w-6 h-6 text-blue-600" />
              3. How We Use Information
            </h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              Webix Infotech processes information with precise, legitimate objectives designed to optimize your digital 
              experience and drive organizational execution:
            </p>
            <ul className="space-y-3 text-gray-700 list-disc list-inside pl-2">
              <li><strong className="text-gray-900">Service Delivery and Scalability:</strong> Building, optimizing, and maintaining client-facing portals, software modules, and corporate solutions customized to specific enterprise agreements.</li>
              <li><strong className="text-gray-900">Technical Communication Dynamics:</strong> Sending dynamic system notifications, structural estimations, service updates, administrative advisories, security alerts, and comprehensive feedback requests.</li>
              <li><strong className="text-gray-900">Algorithmic Improvements & Research:</strong> Analyzing aggregated, depersonalized data pools to refine user interface journeys, optimize page performance, and deploy functional enhancements.</li>
              <li><strong className="text-gray-900">Corporate Marketing and Outreach:</strong> Distributing insights on modern technologies, developmental methodologies, service upgrades, and corporate announcements to subscribed users.</li>
              <li><strong className="text-gray-900">Security and Risk Abatement:</strong> Mitigating server vulnerabilities, monitoring unauthorized system entry points, fighting digital fraud patterns, and maintaining structural digital safety.</li>
            </ul>
          </section>

          {/* 4. Cookies & Tracking Technologies */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Eye className="w-6 h-6 text-blue-600" />
              4. Cookies & Tracking Technologies
            </h2>
            <p className="text-gray-700 leading-relaxed">
              We deploy standard cookie structures and comparable browser state trackers to preserve user session 
              details, capture navigational metrics, and enhance system response times. These text snippets are safely 
              managed through your native operating terminal or browser application. You retain full system authority to 
              restrict or deny cookie allocations through localized system configurations. Please note, choosing to isolate or 
              drop cookies might alter the layout structure or degrade certain interactive functionalities embedded inside our 
              technical landscape.
            </p>
          </section>

          {/* 5. Data Security Architecture */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Lock className="w-6 h-6 text-blue-600" />
              5. Data Security Architecture
            </h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              At Webix Infotech, data security is integrated directly into our infrastructure. We implement layered physical, 
              technical, and structural protocols to prevent data loss, unauthorized access, destructive data alteration, or 
              malicious disclosure:
            </p>
            <ul className="space-y-2 text-gray-700 list-disc list-inside pl-2">
              <li><strong className="text-gray-900">Transport Encryption:</strong> Deployment of industry-standard Secure Sockets Layer (SSL) and Transport Layer Security (TLS) cryptographic channels across all internal and public web pathways.</li>
              <li><strong className="text-gray-900">Identity Access Management (IAM):</strong> Restricting data retrieval rights exclusively to authorized system engineers, data controllers, and managers under strict confidentiality parameters.</li>
              <li><strong className="text-gray-900">Regular Security Scans:</strong> Continuous automated system review processes, code analysis, and malware identification protocols to maintain high infrastructure compliance.</li>
            </ul>
          </section>

          {/* 6. Data Retention Protocols */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Clock className="w-6 h-6 text-blue-600" />
              6. Data Retention Protocols
            </h2>
            <p className="text-gray-700 leading-relaxed">
              We retain your personal metrics strictly for timelines required to execute the explicit technical service 
              parameters highlighted inside this policy or to fulfill binding legal, taxation, and statutory requirements. Upon 
              fulfillment of these objectives, or upon legitimate deletion requests processed under applicable law, your 
              sensitive data undergoes definitive structural erasure, database scrubbing, or full anonymization, ensuring no 
              physical or digital reconstruction can occur within our storage arrays.
            </p>
          </section>

          {/* 7. Third-Party Services & Integrations */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Globe className="w-6 h-6 text-blue-600" />
              7. Third-Party Services & Integrations
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Our digital interfaces utilize highly secure third-party components for advanced analytics, cloud optimization, 
              customer relationship tools, and external content processing. These entities process data exclusively under 
              our explicit transactional commands. They are contractually obligated to maintain absolute privacy 
              compliance and are banned from utilizing your data for independent operational motivations. This policy does 
              not extend to general external networks linked via third-party hyperlinks, and we strongly suggest examining 
              their respective privacy guidelines before engagement.
            </p>
          </section>

          {/* 8. User Rights & Data Control */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Shield className="w-6 h-6 text-blue-600" />
              8. User Rights & Data Control
            </h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              Users who engage with Webix Infotech possess well-defined data oversight privileges in accordance with 
              digital privacy benchmarks:
            </p>
            <ul className="space-y-2 text-gray-700 list-disc list-inside pl-2">
              <li><strong className="text-gray-900">Right to Inspection:</strong> Request full clarity on stored data fields currently preserved in our database architecture.</li>
              <li><strong className="text-gray-900">Right to Rectification:</strong> Demand immediate adjustments or modifications to any outdated, faulty, or missing structural information.</li>
              <li><strong className="text-gray-900">Right to Deletion:</strong> Ask for complete database cleanup and elimination of personal records, subject to overarching contractual or legal constraints.</li>
              <li><strong className="text-gray-900">Right to Restriction:</strong> Command a total freeze on active data processing streams for specific contextual justifications.</li>
            </ul>
          </section>

          {/* 9. Children's Privacy Guidelines */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Smile className="w-6 h-6 text-blue-600" />
              9. Children's Privacy Guidelines
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Our software modules, business architectures, and digital services are built strictly for operational execution 
              by professional enterprises, adults, and individuals aged 18 and above. We do not deliberately source, 
              register, or process records from children under this threshold. If our team identifies an accidental tracking or 
              submission of youthful data records without verified parental authorization, we will rapidly purge that specific 
              dataset from our servers.
            </p>
          </section>

          {/* 10. Changes to This Privacy Policy */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Calendar className="w-6 h-6 text-blue-600" />
              10. Changes to This Privacy Policy
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Webix Infotech reserves the right to revise, modify, or update this Privacy Policy framework to keep pace with 
              changing technologies, legal updates, or service structures. Any update will be transparently detailed on this 
              legal sub-page with a revised update marker prominently showcased. Continued interaction with our technical 
              ecosystem post-revision signifies formal acknowledgment and structural alignment with the modified guidelines.
            </p>
          </section>

          {/* 11. Contact Information & Redressal */}
          <section className="bg-blue-50/70 border border-blue-100 rounded-3xl p-6 sm:p-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
              <Mail className="w-6 h-6 text-blue-600" />
              11. Contact Information & Redressal
            </h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              For any queries, systemic definitions, policy explanations, or data rights assertions, you can directly approach 
              our professional management desk:
            </p>
            
            {/* Contact Details Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 bg-white rounded-2xl p-6 sm:p-8 shadow-sm">
              <div className="space-y-3 text-gray-700">
                <p>
                  <strong className="text-gray-900 text-sm block uppercase tracking-wider text-blue-600">Company</strong> 
                  Webix Infotech India Pvt. Ltd.
                </p>
                <p>
                  <strong className="text-gray-900 text-sm block uppercase tracking-wider text-blue-600">Email</strong> 
                  <a href="mailto:officialwebixinfotech@gmail.com" className="text-blue-600 hover:underline">
                    officialwebixinfotech@gmail.com
                  </a>
                </p>
                <p>
                  <strong className="text-gray-900 text-sm block uppercase tracking-wider text-blue-600">Phone</strong> 
                  +91 9926820304
                </p>
              </div>
              <div className="text-gray-700">
                <p>
                  <strong className="text-gray-900 text-sm block uppercase tracking-wider text-blue-600">Corporate Address</strong> 
                  Aditya Gateway, MR 10 Road, Vijay Nagar, Indore - 452010, Madhya Pradesh, India
                </p>
              </div>
            </div>
          </section>

        </div>

        {/* Footer Note */}
        <div className="mt-8 text-center text-gray-500 text-sm">
          <p>
            This privacy policy framework is strictly configured for Webix Infotech operational structures. 
            All Rights Reserved © 2026.
          </p>
        </div>

      </div>
    </div>
  );
};

export default Privacy;